"""categories and garmants tables

Revision ID: 358983a87ee3
Revises: e99f8ba7c0b3
Create Date: 2025-10-27 18:07:34.371963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358983a87ee3'
down_revision = 'e99f8ba7c0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)

    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_category_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sub_category_name'), ['name'], unique=True)

    op.create_table('garment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['sub_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garment_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_garment_subcategory_id'), ['subcategory_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garment_subcategory_id'))
        batch_op.drop_index(batch_op.f('ix_garment_name'))

    op.drop_table('garment')
    with op.batch_alter_table('sub_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_category_name'))
        batch_op.drop_index(batch_op.f('ix_sub_category_category_id'))

    op.drop_table('sub_category')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))

    op.drop_table('category')
    # ### end Alembic commands ###
