"""looks table

Revision ID: e99f8ba7c0b3
Revises: 9b7243e971a6
Create Date: 2025-10-10 15:27:42.781888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99f8ba7c0b3'
down_revision = '9b7243e971a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('look',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('look', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_look_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('look', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_look_user_id'))

    op.drop_table('look')
    # ### end Alembic commands ###
